name: CI/CD
on:
  push:
    branches:
    - main
jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install npm modules
      run: npm install
    - name: Run ESLint
      run: npm run lint
  tests:
    needs: static-analysis
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Cypress tests in parallel 🧪
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
  deploy:
    needs: tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./src/ s3://cypress-simulator --delete
